#!/usr/bin/env python

import rospy
from std_msgs.msg import String
from sensor_msgs.msg import LaserScan

#defines publisher node
def talker():
    serial_port = '/dev/ttyUSB0'
    serial_baudrate = '9600'
    rospy.init_node('Lidar_Data', anonymous=True)
    lidar_pub = rospy.Publisher('scan', LaserScan, queue_size=50)

    rate = rospy.Rate(2) # 2hz

    while not rospy.is_shutdown():
        lidar = LaserScan()
        lidar.header.stamp = rospy.Time.now()
        lidar.frame_id = 'Lidar'

        rospy.loginfo(lidar)
        lidar_pub.publish(lidar)
        rate.sleep()





           



    
    
    
