#!/usr/bin/env python

import rospy
from sensor_msgs.msg import LaserScan

#defines subscriber node
def listener():
    rospy.init_node('Camera_data', anonymous=True)

    rospy.Subscriber('Lidar_Data', String, callback)

    # spin() simply keeps python from exiting until this node is stopped
    rospy.spin()
